spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.63.214:3306/demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 45628852
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: update


